// This file was auto-generated by quicktype.

export interface WeaponSkin {
    _id:            number;
    id:             string;
    name:           string;
    description:    string;
    rarity:         number;
    type:           Type;
    is_sublimation: boolean;
    group:          Group | null;
    item_id:        number;
    tag_type?:      string;
    icon_path:      string;
    image_path:     string;
}

export interface Group {
    _id:      number;
    name:     string;
    priority: number;
}

export interface Type {
    id:   string;
    name: string;
}
